Repository home-assistant-libs/python-supervisor-client, pull requests merged in 2024-10, with the labels that each got.

#14 Add supervisor APIs to client library
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/base.py
  aiohasupervisor/models/supervisor.py
  aiohasupervisor/root.py
  aiohasupervisor/supervisor.py
  tests/fixtures/supervisor_info.json
  tests/fixtures/supervisor_stats.json
  tests/test_supervisor.py
Labels: new-feature

#15 Add core APIs to client library
  aiohasupervisor/homeassistant.py
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/addons.py
  aiohasupervisor/models/homeassistant.py
  aiohasupervisor/root.py
  tests/fixtures/homeassistant_info.json
  tests/fixtures/homeassistant_stats.json
  tests/test_homeassistant.py
Labels: new-feature

#12 Add Supervisor's OS APIs
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/os.py
  aiohasupervisor/os.py
  aiohasupervisor/root.py
  tests/fixtures/os_datadisk_list.json
  tests/fixtures/os_green_info.json
  tests/fixtures/os_info.json
  tests/fixtures/os_yellow_info.json
  tests/test_os.py
Labels: new-feature

#18 Add backups APIs to client library
  aiohasupervisor/backups.py
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/backups.py
  aiohasupervisor/models/base.py
  aiohasupervisor/root.py
  tests/fixtures/backup_background.json
  tests/fixtures/backup_foreground.json
  tests/fixtures/backup_info.json
  tests/fixtures/backup_restore.json
  tests/fixtures/backups_info.json
  tests/fixtures/backups_list.json
  tests/test_backups.py
Labels: new-feature

#16 Add discovery APIs from supervisor
  aiohasupervisor/discovery.py
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/discovery.py
  aiohasupervisor/root.py
  tests/fixtures/discovery_get.json
  tests/fixtures/discovery_list.json
  tests/fixtures/discovery_set.json
  tests/test_discovery.py
Labels: new-feature

#21 Remove DiscoveryList from exposed models
  aiohasupervisor/models/__init__.py
Labels: bugfix

#20 Add network APIs from supervisor
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/network.py
  aiohasupervisor/network.py
  aiohasupervisor/root.py
  tests/fixtures/network_access_points.json
  tests/fixtures/network_info.json
  tests/fixtures/network_interface_info.json
  tests/test_network.py
Labels: new-feature

#19 Add Host APIs from supervisor
  aiohasupervisor/host.py
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/host.py
  aiohasupervisor/root.py
  tests/fixtures/host_info.json
  tests/fixtures/host_services.json
  tests/test_host.py
Labels: new-feature

#23 Set appropriate timeouts for clients without option
  aiohasupervisor/addons.py
  aiohasupervisor/backups.py
  aiohasupervisor/client.py
  aiohasupervisor/const.py
  aiohasupervisor/discovery.py
  aiohasupervisor/homeassistant.py
  aiohasupervisor/host.py
  aiohasupervisor/os.py
  aiohasupervisor/resolution.py
  aiohasupervisor/root.py
  aiohasupervisor/store.py
  aiohasupervisor/supervisor.py
Labels: breaking-change

#22 Rename action methods without verb
  aiohasupervisor/addons.py
  aiohasupervisor/backups.py
  aiohasupervisor/homeassistant.py
  aiohasupervisor/host.py
  aiohasupervisor/os.py
  aiohasupervisor/supervisor.py
  tests/test_addons.py
  tests/test_backups.py
  tests/test_homeassistant.py
  tests/test_host.py
  tests/test_os.py
  tests/test_supervisor.py
Labels: breaking-change

#24 Add py.typed
  aiohasupervisor/py.typed
Labels: new-feature

#25 Update pyproject.toml to include py.typed
  pyproject.toml
Labels: bugfix
