Repository home-assistant-libs/python-supervisor-client, pull requests merged in 2025-01, with the labels that each got.

#41 Add jobs API to library
  aiohasupervisor/jobs.py
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/jobs.py
  aiohasupervisor/root.py
  tests/fixtures/jobs_get_job.json
  tests/fixtures/jobs_info.json
  tests/test_jobs.py
Labels: new-feature

#43 Add filename input to backup APIs
  aiohasupervisor/models/backups.py
  tests/test_backups.py
Labels: new-feature

#44 Add filename input to upload backup API
  aiohasupervisor/backups.py
  aiohasupervisor/models/backups.py
  tests/test_backups.py
Labels: new-feature

#45 Add location attributes field to backup model
  aiohasupervisor/models/backups.py
  tests/fixtures/backup_info.json
  tests/fixtures/backup_info_location_attributes.json
  tests/fixtures/backup_info_no_homeassistant.json
  tests/fixtures/backup_info_with_extra.json
  tests/fixtures/backup_info_with_locations.json
  tests/fixtures/backups_info.json
  tests/fixtures/backups_list.json
  tests/fixtures/backups_list_location_attributes.json
  tests/test_backups.py
Labels: new-feature

#46 Fix location attributes base class
  aiohasupervisor/models/backups.py
Labels: bugfix

#47 Cleanup backup model after changes
  aiohasupervisor/backups.py
  aiohasupervisor/models/__init__.py
  aiohasupervisor/models/backups.py
  tests/test_backups.py
Labels: breaking-change, refactor

#48 Make job id a proper UUID in response model
  aiohasupervisor/models/backups.py
  tests/test_backups.py
Labels: breaking-change, bugfix

#49 Add created field to jobs
  aiohasupervisor/models/jobs.py
  tests/fixtures/jobs_get_job.json
  tests/fixtures/jobs_info.json
  tests/test_jobs.py
Labels: new-feature
