Repository home-assistant-libs/python-supervisor-client, pull requests merged in 2025-04, with the labels that each got.

#51 Add dependabot config file
  .github/dependabot.yml
Labels: ci

#77 Homeassistant machine and arch can be None
  aiohasupervisor/models/homeassistant.py
Labels: bugfix

#76 Disk life time can be `None`
  aiohasupervisor/models/host.py
Labels: bugfix

#50 Add API for /os/config/swap endpoints
  aiohasupervisor/models/os.py
  aiohasupervisor/os.py
  tests/fixtures/os_config_swap.json
  tests/test_os.py
Labels: new-feature

#82 Vlan parent can be `None`
  aiohasupervisor/models/network.py
Labels: bugfix

#85 Add country field to Supervisor info
  aiohasupervisor/models/supervisor.py
  tests/fixtures/supervisor_info.json
  tests/test_supervisor.py
Labels: new-feature

#90 Add reload updates for main components
  aiohasupervisor/root.py
  tests/test_root.py
Labels: new-feature

#93 Add country field to Supervisor options
  aiohasupervisor/models/supervisor.py
  tests/test_supervisor.py
Labels: new-feature
